# Nombres en español para los códigos ISO-3 más frecuentes del dataset.
# Los códigos sin traducción se muestran tal cual en el dashboard.
COUNTRY_NAMES_ES = {
    "PRT": "Portugal",
    "ESP": "España",
    "FRA": "Francia",
    "GBR": "Reino Unido",
    "DEU": "Alemania",
    "ITA": "Italia",
    "IRL": "Irlanda",
    "BEL": "Bélgica",
    "NLD": "Países Bajos",
    "USA": "Estados Unidos",
    "BRA": "Brasil",
    "CHE": "Suiza",
    "CHN": "China",
    "AUT": "Austria",
    "SWE": "Suecia",
    "POL": "Polonia",
    "RUS": "Rusia",
    "NOR": "Noruega",
    "DNK": "Dinamarca",
    "FIN": "Finlandia",
    "AUS": "Australia",
    "ROU": "Rumanía",
    "LUX": "Luxemburgo",
    "CZE": "Chequia",
    "ARG": "Argentina",
    "MEX": "México",
    "MAR": "Marruecos",
    "JPN": "Japón",
    "IND": "India",
    "KOR": "Corea del Sur",
    "TUR": "Turquía",
    "HUN": "Hungría",
    "GRC": "Grecia",
    "ISR": "Israel",
    "CHL": "Chile",
    "COL": "Colombia",
    "VEN": "Venezuela",
    "URY": "Uruguay",
    "PER": "Perú",
    "ECU": "Ecuador",
    "BOL": "Bolivia",
    "PRY": "Paraguay",
    "CRI": "Costa Rica",
    "PAN": "Panamá",
    "DOM": "República Dominicana",
    "CUB": "Cuba",
    "GTM": "Guatemala",
    "HND": "Honduras",
    "SLV": "El Salvador",
    "PRI": "Puerto Rico",
    "CAN": "Canadá",
    "UKR": "Ucrania",
    "SRB": "Serbia",
    "HRV": "Croacia",
    "SVN": "Eslovenia",
    "SVK": "Eslovaquia",
    "BGR": "Bulgaria",
    "EST": "Estonia",
    "LVA": "Letonia",
    "LTU": "Lituania",
    "ISL": "Islandia",
    "MLT": "Malta",
    "CYP": "Chipre",
    "AGO": "Angola",
    "MOZ": "Mozambique",
    "CPV": "Cabo Verde",
    "ZAF": "Sudáfrica",
    "EGY": "Egipto",
    "TUN": "Túnez",
    "DZA": "Argelia",
    "NGA": "Nigeria",
    "ARE": "Emiratos Árabes Unidos",
    "SAU": "Arabia Saudita",
    "QAT": "Catar",
    "KWT": "Kuwait",
    "THA": "Tailandia",
    "SGP": "Singapur",
    "MYS": "Malasia",
    "IDN": "Indonesia",
    "PHL": "Filipinas",
    "VNM": "Vietnam",
    "HKG": "Hong Kong",
    "TWN": "Taiwán",
    "NZL": "Nueva Zelanda",
}


def country_options(codes):
    """[(código, etiqueta)] ordenados: traducidos primero por nombre, resto por código."""
    named = [(c, COUNTRY_NAMES_ES[c]) for c in codes if c in COUNTRY_NAMES_ES]
    unnamed = [(c, c) for c in codes if c not in COUNTRY_NAMES_ES]
    return sorted(named, key=lambda x: x[1]) + sorted(unnamed)
